"""add_dataforms

Revision ID: 393e6319018d
Revises: 001_initial
Create Date: 2026-02-20 11:19:30.695903

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '393e6319018d'
down_revision: Union[str, None] = '001_initial'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('form_schemas',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('web_id', sa.String(length=36), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['web_id'], ['webs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name', 'web_id', name='uq_form_schema_name_web')
    )
    op.create_index(op.f('ix_form_schemas_name'), 'form_schemas', ['name'], unique=False)
    op.create_index(op.f('ix_form_schemas_web_id'), 'form_schemas', ['web_id'], unique=False)
    op.create_table('form_fields',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('schema_id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('label', sa.String(length=256), nullable=False),
    sa.Column('field_type', sa.String(length=32), nullable=False),
    sa.Column('options', sa.Text(), nullable=False),
    sa.Column('default_value', sa.Text(), nullable=False),
    sa.Column('is_required', sa.Boolean(), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['schema_id'], ['form_schemas.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('schema_id', 'name', name='uq_form_field_schema_name')
    )
    op.create_index(op.f('ix_form_fields_schema_id'), 'form_fields', ['schema_id'], unique=False)
    op.alter_column('attachments', 'uploaded_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('topic_versions', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.add_column('topics', sa.Column('form_schema_id', sa.String(length=36), nullable=True))
    op.alter_column('topics', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.create_index(op.f('ix_topics_form_schema_id'), 'topics', ['form_schema_id'], unique=False)
    op.create_foreign_key(None, 'topics', 'form_schemas', ['form_schema_id'], ['id'], ondelete='SET NULL')
    op.alter_column('users', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('users', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('webs', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_constraint(op.f('webs_name_key'), 'webs', type_='unique')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(op.f('webs_name_key'), 'webs', ['name'], postgresql_nulls_not_distinct=False)
    op.alter_column('webs', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('users', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('users', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.drop_constraint(None, 'topics', type_='foreignkey')
    op.drop_index(op.f('ix_topics_form_schema_id'), table_name='topics')
    op.alter_column('topics', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.drop_column('topics', 'form_schema_id')
    op.alter_column('topic_versions', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('attachments', 'uploaded_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.drop_index(op.f('ix_form_fields_schema_id'), table_name='form_fields')
    op.drop_table('form_fields')
    op.drop_index(op.f('ix_form_schemas_web_id'), table_name='form_schemas')
    op.drop_index(op.f('ix_form_schemas_name'), table_name='form_schemas')
    op.drop_table('form_schemas')
    # ### end Alembic commands ###
